import io
from typing import Dict, Any

class PDFGeneratorService:
    @staticmethod
    def generate_itinerary_pdf(itinerary: Dict[str, Any]) -> io.BytesIO:
        """Generates a professional PDF itinerary using ReportLab."""
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.lib import colors
            from reportlab.platypus import (
                SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
            )
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.units import inch
        except ImportError as err:
            raise RuntimeError("ReportLab package is required for PDF generation. Please install reportlab.") from err

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=36,
            leftMargin=36,
            topMargin=36,
            bottomMargin=36
        )

        styles = getSampleStyleSheet()
        
        # Custom Brand Palette
        COLOR_PRIMARY = colors.HexColor("#1e1b4b")   # Deep Indigo
        COLOR_SECONDARY = colors.HexColor("#0284c7") # Ocean Cyan
        COLOR_ACCENT = colors.HexColor("#f59e0b")    # Amber
        COLOR_TEXT = colors.HexColor("#1f2937")      # Charcoal Body Text
        COLOR_LIGHT_BG = colors.HexColor("#f8fafc")  # Off-white

        # Custom Typography Styles
        style_title = ParagraphStyle(
            'DocTitle',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=24,
            leading=28,
            textColor=COLOR_PRIMARY,
            spaceAfter=6
        )

        style_subtitle = ParagraphStyle(
            'DocSubtitle',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=11,
            leading=14,
            textColor=colors.HexColor("#475569"),
            spaceAfter=15
        )

        style_heading = ParagraphStyle(
            'SectionHeading',
            parent=styles['Heading2'],
            fontName='Helvetica-Bold',
            fontSize=14,
            leading=18,
            textColor=COLOR_SECONDARY,
            spaceBefore=14,
            spaceAfter=8
        )

        style_body = ParagraphStyle(
            'BodyTextCustom',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=9.5,
            leading=13,
            textColor=COLOR_TEXT
        )

        style_body_bold = ParagraphStyle(
            'BodyTextBold',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=9.5,
            leading=13,
            textColor=COLOR_PRIMARY
        )

        story = []

        # 1. Header Banner
        trip_title = itinerary.get("trip_title", "Travel Itinerary")
        destination = itinerary.get("destination", "Global Destination")
        duration = itinerary.get("duration_days", 1)
        travelers = itinerary.get("travelers_count", 1)
        currency = itinerary.get("currency", "USD")
        
        story.append(Paragraph(f"✈️ {trip_title}", style_title))
        story.append(Paragraph(
            f"<b>Destination:</b> {destination} &nbsp;|&nbsp; <b>Duration:</b> {duration} Days &nbsp;|&nbsp; "
            f"<b>Travelers:</b> {travelers} &nbsp;|&nbsp; <b>Generated by TravelGPT</b>",
            style_subtitle
        ))
        story.append(HRFlowable(width="100%", thickness=1.5, color=COLOR_SECONDARY, spaceAfter=15))

        # 2. Executive Summary Box
        summary_text = itinerary.get("summary", "Your custom trip itinerary.")
        story.append(Paragraph("Executive Summary", style_heading))
        summary_table = Table(
            [[Paragraph(summary_text, style_body)]],
            colWidths=[7.2 * inch]
        )
        summary_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), COLOR_LIGHT_BG),
            ('BOX', (0, 0), (-1, -1), 1, colors.HexColor("#e2e8f0")),
            ('PADDING', (0, 0), (-1, -1), 10),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ]))
        story.append(summary_table)
        story.append(Spacer(1, 12))

        # 3. Cost Estimate Summary Table
        cost_est = itinerary.get("cost_estimate", {})
        if cost_est:
            story.append(Paragraph("Estimated Trip Budget Breakdown", style_heading))
            tot_cost = cost_est.get("total_estimated_cost", 0.0)
            tar_budget = cost_est.get("target_budget", 0.0)
            status = cost_est.get("budget_status", "On Budget")
            
            cost_summary_data = [
                [Paragraph("Target Budget", style_body_bold), Paragraph(f"{currency} {tar_budget:,.2f}", style_body),
                 Paragraph("Est. Total Cost", style_body_bold), Paragraph(f"{currency} {tot_cost:,.2f}", style_body),
                 Paragraph("Budget Status", style_body_bold), Paragraph(f"<b>{status}</b>", style_body)]
            ]
            cost_summary_table = Table(cost_summary_data, colWidths=[1.2*inch, 1.2*inch, 1.2*inch, 1.2*inch, 1.2*inch, 1.2*inch])
            cost_summary_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#eff6ff")),
                ('BOX', (0, 0), (-1, -1), 1, colors.HexColor("#bfdbfe")),
                ('PADDING', (0, 0), (-1, -1), 6),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ]))
            story.append(cost_summary_table)
            story.append(Spacer(1, 10))

            # Itemized Cost Table
            breakdown = cost_est.get("breakdown", [])
            if breakdown:
                cost_table_data = [
                    [Paragraph("Expense Category", style_body_bold), Paragraph("Estimated Cost", style_body_bold), Paragraph("Share", style_body_bold), Paragraph("Details & Notes", style_body_bold)]
                ]
                for item in breakdown:
                    cat = item.get("category", "")
                    amt = item.get("amount", 0.0)
                    pct = item.get("percentage", 0.0)
                    notes = item.get("notes", "")
                    cost_table_data.append([
                        Paragraph(cat, style_body),
                        Paragraph(f"{currency} {amt:,.2f}", style_body),
                        Paragraph(f"{pct}%", style_body),
                        Paragraph(notes, style_body)
                    ])
                
                cost_table = Table(cost_table_data, colWidths=[1.8*inch, 1.3*inch, 0.8*inch, 3.3*inch])
                cost_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), COLOR_PRIMARY),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                    ('PADDING', (0, 0), (-1, -1), 5),
                ]))
                story.append(cost_table)
                story.append(Spacer(1, 15))

        # 4. Day by Day Schedule
        story.append(Paragraph("Day-by-Day Detailed Itinerary", style_heading))
        days = itinerary.get("days", [])
        
        for d in days:
            day_num = d.get("day", 1)
            theme = d.get("theme", "")
            story.append(Paragraph(f"<b>Day {day_num}: {theme}</b>", ParagraphStyle('DayHeader', parent=styles['Heading3'], fontSize=11, leading=14, textColor=COLOR_PRIMARY, spaceBefore=8, spaceAfter=4)))
            
            acts = d.get("activities", [])
            act_rows = [
                [Paragraph("Time", style_body_bold), Paragraph("Activity & Description", style_body_bold), Paragraph("Location", style_body_bold), Paragraph("Est. Cost", style_body_bold)]
            ]
            for act in acts:
                time_s = act.get("time_slot", "Morning")
                title = act.get("title", "")
                desc = act.get("description", "")
                loc = act.get("location", "")
                cost_v = act.get("estimated_cost", 0.0)
                
                content_p = Paragraph(f"<b>{title}</b><br/>{desc}", style_body)
                act_rows.append([
                    Paragraph(time_s, style_body),
                    content_p,
                    Paragraph(loc, style_body),
                    Paragraph(f"{currency} {cost_v:.2f}", style_body)
                ])
            
            act_table = Table(act_rows, colWidths=[1.1*inch, 3.6*inch, 1.4*inch, 1.1*inch])
            act_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
                ('PADDING', (0, 0), (-1, -1), 5),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ]))
            story.append(act_table)
            
            # Tips
            tips = d.get("insider_tips", [])
            if tips:
                tip_str = " &bull; ".join(tips)
                story.append(Paragraph(f"💡 <i>Insider Tips:</i> {tip_str}", ParagraphStyle('Tips', parent=style_body, fontSize=8.5, textColor=colors.HexColor("#475569"), spaceBefore=3, spaceAfter=8)))
            else:
                story.append(Spacer(1, 8))

        # Build PDF
        doc.build(story)
        buffer.seek(0)
        return buffer

pdf_generator_service = PDFGeneratorService()
